// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWCQu4wf5FhWWmkaw89vIVXAAbwU8HrT0',
    appId: '1:357658157611:web:ce2a171dd6b0c22a7dc06e',
    messagingSenderId: '357658157611',
    projectId: 'por-que-esse-nome',
    authDomain: 'por-que-esse-nome.firebaseapp.com',
    storageBucket: 'por-que-esse-nome.appspot.com',
    measurementId: 'G-H6DE1XHF55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1GWZIq4alZ5UHtVFToIn2YrGmEYQs3n8',
    appId: '1:357658157611:android:cabdc7a3b65be3ea7dc06e',
    messagingSenderId: '357658157611',
    projectId: 'por-que-esse-nome',
    storageBucket: 'por-que-esse-nome.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2qc8zbcKWPkkMbUT9alZofrt2m_Vki6k',
    appId: '1:357658157611:ios:acd718f6b43834e07dc06e',
    messagingSenderId: '357658157611',
    projectId: 'por-que-esse-nome',
    storageBucket: 'por-que-esse-nome.appspot.com',
    iosBundleId: 'com.example.pqessenome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWCQu4wf5FhWWmkaw89vIVXAAbwU8HrT0',
    appId: '1:357658157611:web:d57fedc715d4c2f67dc06e',
    messagingSenderId: '357658157611',
    projectId: 'por-que-esse-nome',
    authDomain: 'por-que-esse-nome.firebaseapp.com',
    storageBucket: 'por-que-esse-nome.appspot.com',
    measurementId: 'G-LL14LFW3TY',
  );

}